finalSite/finalSite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import staticfiles
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/', include('finalapp.urls')),
    url(r'^movie/', include('movie_list.urls')),
    url(r'^news/', include('news_list.urls')),
    url(r'^intro/', include('intro_list.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finalSite/finalapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

finalSite/finalapp/models.py
from __future__ import unicode_literals
from django.db import models

# Create your models here.

finalSite/movie_list/models.py
from __future__ import unicode_literals
from django.db import models

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=20)
    def __str__(self):
        return self.title
    
class Movie(models.Model):
    ctitle = models.CharField(max_length=20)
    title = models.CharField(max_length=100)
    image = models.ImageField(null=False, blank=False)
    director = models.CharField(max_length=100, default="無")
    actors = models.TextField(default="無")
    length = models.CharField(max_length=20, default="2小時")
    movietype = models.CharField(max_length=100, default="動畫")
    videourl = models.URLField(max_length=200, default="www.youtube.com")
    introduction = models.TextField(default="電影介紹")
    pub_date = models.DateField('上映日期')
    date = models.TextField(default="00:00")
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    def __str__(self):
        return self.ctitle
    class Meta:
        ordering = ["-pub_date"]

finalSite/finalapp/views.py
from __future__ import unicode_literals
from django.shortcuts import render, render_to_response
from django.http import Http404
from movie_list.models import Movie, Category
from news_list.models import News

# Create your views here.
def index(request):
    categories = Category.objects.all()
    news = News.objects.all()
    return render_to_response('finalapp/index.html', locals())

finalSite/finalapp/templates/finalapp/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Motto 影城</title>
    <link rel="shortcut icon" href="{% static 'img/ico/icon.png' %}">

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/business-casual.css' %}" rel="stylesheet">

     <link href="{% static 'css/index.css' %}" rel="stylesheet">
    
    <!-- EDAEDAEDAEDAEDAEDAEDAEDAEDAEDAEDAEDAEDAEDAEDAEDAEDA -->
    <link href="{% static 'css/inside.css' %}" rel="stylesheet">
    <!-- EDAEDAEDAEDAEDAEDAEDAEDAEDAEDAEDAEDAEDAEDAEDAEDAEDA -->
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body style="font-family:微軟正黑體;">


     <nav   role="navigation" class="navbar  " style="background-color:rgba(1,1, 1, 1);">
        <div class="container">

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse"   >
                 <ul class="nav navbar-nav" >
                    <li >
                       <div class="dropdown">
                                 <a href="#"><button class="dropbtn" style="color: black;">MOTTO</button></a>
                            </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>


    <!-- Navigation -->
    <nav   role="navigation" class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="/index/">Motto</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"   >
                <ul class="nav navbar-nav" >
                  
                    <li >
                       <div class="dropdown">
                                 <a href="/index/"><button class="dropbtn" >MOTTO</button></a>
                            </div>
                    </li>
                     
                    <li>
                    <div class="dropdown">
                         <button class="dropbtn" >電影介紹</button>
                          <div class="dropdown-content">
                                 <a href="/movie/online/">現正上映電影</a>
                                 <a href="/movie/comingsoon/">即將上映電影</a>
                                </div> 
                         </div>
                    </li>

                    <li>
                    <div class="dropdown">
                                 <button class="dropbtn">排行榜</button>
                             <div class="dropdown-content">
                                <a href="/movie/hotweek/">本周最熱</a>
                                <a href="/movie/hotmonth/">本月最熱<img src="{% static 'img/ico/fire.ico' %}"></a>
                             </div>
                            </div>
                       
                    </li>
                     <li>
                     <div class="dropdown">
                                 <button class="dropbtn">好康優惠</button>
                             <div class="dropdown-content">
                                <a href="/news/">最新訊息</a>
                                <a href="/news/foodsets/">超值套票</a>
                                <a href="/news/card/">卡友優惠</a>
                                <a href="/news/group/"> 購買團票</a>
                             </div>
                            </div>
                       
                    </li>
                     <li>
                     <div class="dropdown">
                                 <button class="dropbtn">影城介紹</button>
                             <div class="dropdown-content">
                                <a href="/intro/about/">關於我們</a>
                                <a href="/intro/contact/">意見信箱</a>
                                <a href="/intro/device/">設備介紹</a>
                                <a href="/intro/qanda/">常見Q&A</a>
                             </div>
                            </div>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->

        </div>
        <!-- /.container -->
    </nav>

     



        <div class="row"  >
          
                <div class="col-lg-12 text-center"   ">
                    <div id="carousel-example-generic" class="carousel slide">
                        <!-- Indicators -->
                        <ol class="carousel-indicators hidden-xs">
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                             <li data-target="#carousel-example-generic" data-slide-to="3"></li>
                        </ol>

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner" >
                            <div class="item active">
                                <img class="img-responsive img-full" src="{% static 'img/home_page1.jpg' %}" >
                            </div>
                            <div class="item">
                                <img class="img-responsive img-full" src="{% static 'img/home_page2.jpg' %}">
                            </div>
                            <div class="item">
                                <img class="img-responsive img-full" src="{% static 'img/home_page3.jpg' %}">
                            </div>
                             <div class="item">
                                <img class="img-responsive img-full" src="{% static 'img/home_page4.jpg' %}">
                            </div>
                        </div>

                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                           
                            <span class="icon-prev"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                           
                            <span class="icon-next"></span>
                        </a>
                    </div>  
                </div>
            
        </div>



 
    <!--class="intro-text text-center" 置中用 -->
<div class="container" style="margin-top: 4%;background-color:rgba(0,0,0,0.5);  border-radius:15px;  padding: 5%;   ">
        <div class="row" >
          
                <div class="col-lg-6 " >
                    
                    <h1 id="textStyle1">最新消息 </h1>
                    <hr>
                    {% for news in news %}
                    {% if forloop.counter0 < 5 %}
                    <p><a href="/news/{{ news.id }}" id="textStyle2"><b> {{ news.timestamp.date| date:"Y/m/d" }}</b>　{{ news.title }}</a></p>
                    {% endif %}
                    {% endfor %}
                </div>

                  <div class="col-lg-6 text-center" >
                  <div id="carousel-example-generic3" class="carousel slide">
                        <!-- Indicators -->
                        <ol class="carousel-indicators hidden-xs">
                            <li data-target="#carousel-example-generic3" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic3" data-slide-to="1"></li>
                            <li data-target="#carousel-example-generic3" data-slide-to="2"></li>
                              
                        </ol>

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner" >
                           
                            <div class="item active">
                                <img class="img-responsive img-full" src="{% static 'img/slide-1.jpg' %}" alt="slide-1.jpg" >
                            </div>
                            <div class="item">
                                <img class="img-responsive img-full" src="{% static 'img/slide-2.jpg' %}" alt="slide-2.jpg">
                            </div>
                            <div class="item">
                                <img class="img-responsive img-full" src="{% static 'img/slide-3.jpg' %}" alt="slide-3.jpg">
                            </div>
                        </div>

                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel-example-generic3" data-slide="prev">
                           
                            <span class="icon-prev"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic3" data-slide="next">
                           
                            <span class="icon-next"></span>
                        </a>
                    </div>  
                
            </div>  
      
  </div>

</div>


<div class="container" style="margin-top: 4%; ">
        <div class="row"  >
            <div class="box" style="background-color:rgba(0,0,0,0); padding: 5%;  ">
                <div class="col-lg-12">
                    
                    <h1 class="text-center" id="textStyle3">現正熱映中</h1>
                    <hr>
                    <big>
                    <p align="right" style="margin-right:2.5em">
                    <a href="/movie/online/" style="text-decoration:none;color: white; text-shadow: 0.1em 0.1em 0.18em red;font-weight: bold; ">MORE</a>
                    </p>
                    </big>
                    <ul class="hotList">
                        {% for c in categories %}
                        {% if c.title == '現正熱映中' %}
                        {% for movie in c.movie_set.all %}
                        {% if movie.image and forloop.counter0 < 4 %}
                        <li>
                          <figure style="height: 240px;"><a href="/movie/{{ movie.id }}" style="height: 240px;"><img src="{{ movie.image.url }}" alt="{{ movie.ctitle }}" title="{{ movie.ctitle }}" style="height: 100%; width: auto; margin-left: -1px;"></a></figure>
                          <section class="infoArea">
                            <h2><a href="/movie/{{ movie.id }}" id="textStyle4">{{ movie.ctitle }}</a></h2>
                            <h3 id="textStyle5">{{ movie.title }}</h3>
                          </section>
                        </li>
                        {% endif %}
                        {% endfor %}
                        {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
            
        </div>   
     
    <!-- /.container -->

    <footer style="background-color:rgba(100,100, 120, 0.3);">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center" >
                    <p>Copyright &copy; Motto Website 2017</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    
    
    <!-- EDAEDAEDAEDAEDAEDAEDAEDAEDAEDAEDAEDAEDAEDAEDAEDAEDA -->
    <script src="{% static 'js/twcaseal_v3.js' %}"></script>
    <script src="{% static 'js/helper.js' %}"></script>
    <script src="{% static 'js/inside.js' %}"></script>
    <script src="{% static 'js/jquery.validationEngine.js' %}"></script>
    <script src="{% static 'js/jquery.validationEngine-zh_TW.js' %}"></script>
    <script src="{% static 'js/jquery-migrate-1.1.0.js' %}"></script>
    <script src="{% static 'js/photoswipe.min.js' %}"></script>
    <script src="{% static 'js/photoswipe-ui-default.min.js' %}"></script>
    <script src="{% static 'js/scrolltopcontrol.js' %}"></script>
    <script src="{% static 'js/share.js' %}"></script>
    <script src="{% static 'js/jquery-2.1.0.min.js' %}"></script>
    <!-- EDAEDAEDAEDAEDAEDAEDAEDAEDAEDAEDAEDAEDAEDAEDAEDAEDA -->
    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>

</body>

</html>